lint-conf: lintconf.yaml
chart-yaml-schema: chart_schema.yaml
validate-maintainers: false
validate-chart-schema: true
validate-yaml: true
check-version-increment: false
all: false
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-repo-extra-args: []
chart-dirs:
  - charts
excluded-charts: []
helm-extra-args: --timeout 300
upgrade: true
skip-missing-values: false
namespace: default
release-label: release
exclude-deprecated: false
kubectl-timeout: 120s
skip-clean-up: true
