{{- if eq .Values.azureKeyVaultSecrets.type "external-secrets" }}
{{- range $keyVault := .Values.azureKeyVaultSecrets.azureKeyVaults }}
{{- $azureKeyVaultURL := default $keyVault.vaultUrl (print "https://" .azureKeyVaultName ".vault.azure.net/") }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ .azureKeyVaultName | lower  }}-secret-store"
  labels:
    {{- include "kubeit-secrets-chart.labels" $ | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      # URL of your vault instance - https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: {{ $azureKeyVaultURL | lower }}
      serviceAccountRef:
        name: "{{ $.Release.Name | lower }}-service-account"

{{- range $secret := .secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $.Values.app }}-{{ .k8sSecretName | lower  }}"
  labels:
    {{- include "kubeit-secrets-chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ $keyVault.azureKeyVaultName | lower }}-secret-store"
    kind: SecretStore
  target:
    name: "{{ .k8sSecretName }}"
    creationPolicy: Owner
  data:
  {{- range $data:= .data }}
    - secretKey: {{ .k8sSecretKey }}
      remoteRef:
        key: "{{ .azureKeyVaultSecretName }}"
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
