---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kubeit-secrets-chart.labels" $ | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ $.Values.azureKeyVaultSecrets.clientId }}
    azure.workload.identity/tenant-id: {{ $.Values.azureKeyVaultSecrets.tenantId }}
  name: "{{ $.Release.Name | lower }}-service-account"
