{{ range .Values.externalSecrets }}
{{- if or $.Values.persistentVolume.external (ne .name "rabbitmq-storageaccount-secret") }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name | trunc 63 | trimSuffix "-" | lower }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "kubeit-rabbit-chart.fullname" $ }}
    kind: SecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
  {{- if eq .type "certificate" }}
  template:
    type: kubernetes.io/tls
    engineVersion: v2
    data:
      tls.crt: '{{ "{{ .data | filterPEM \"CERTIFICATE\" }}" }}'
      tls.key: '{{ "{{ .data | filterPEM \"PRIVATE KEY\" }}" }}'
  {{- end }}
  {{- if eq .dataType "stringData" }}
  stringData:
  {{- else }}
  data:
  {{- end }}
  {{- range $data := .data }}
    {{- if and $data.key $data.azureSecretName }}
    - secretKey: {{ $data.key }}
      remoteRef:
        key: {{ $data.azureSecretName }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
