{{ range .Values.externalSecrets }}
{{- if or  $.Values.persistentVolume.external  (( ne .name "rabbitmq-storageaccount-secret")) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name | trunc 63 | trimSuffix "-" | lower }}
  labels:
  {{- include "kubeit-rabbit-chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "kubeit-rabbit-chart.fullname" $ }}
    kind: SecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
    {{- if eq .type "certificate" }}
    template:
      type: kubernetes.io/tls
      engineVersion: v2
    {{- end }}
  data:
    {{- if eq .type "certificate" }}
    {{- range $data := .data }}
    tls.crt: "{{ $data.azureSecretName | b64dec | pkcs12cert | pemCertificate }}"
    tls.key: "{{ $data.azureSecretName | b64dec | pkcs12key | pemPrivateKey }}"
    {{- end }}
    {{- end }}
    {{- range $data := .data }}
    - secretKey: {{ $data.key }}
      remoteRef:
        key: {{ $data.azureSecretName }}
    {{- end }}
{{- end }}
{{- end }}
