{{ range .Values.externalSecrets }}
{{- if or $.Values.persistentVolume.external (ne .name "rabbitmq-storageaccount-secret") }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name | trunc 63 | trimSuffix "-" | lower }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "kubeit-rabbit-chart.fullname" $ }}
    kind: SecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
    {{- if eq .type "certificate" }}
    template:
      type: kubernetes.io/tls
    {{- end }}
  data:
    {{- if eq .type "certificate" }}
    {{- range .data }}
    - secretKey: tls.crt
      remoteRef:
        key: {{ .azureSecretName }}
        property: cert
        decodingStrategy: Base64
        conversionFormat: PEM_CERTIFICATE
    - secretKey: tls.key
      remoteRef:
        key: {{ .azureSecretName }}
        property: cert
        decodingStrategy: Base64
        conversionFormat: PEM_PRIVATE_KEY
    {{- end }}
    {{- else }}
    {{- range .data }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .azureSecretName }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
