---
{{- if .Values.pdb.create }}
{{- if ge .Values.rabbitmqCluster.spec.replicas 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-rabbitmq
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-%s" .Release.Name .Values.tenantName | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
