apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-rabbitmq
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{- include "kubeit-rabbit-chart.labels" . | nindent 4 }}
