---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "kubeit-rabbit-chart.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "kubeit-rabbit-chart.selectorLabels" . | nindent 6 }}
  mtls:
    mode: PERMISSIVE
