{{- if .Values.persistentVolume.external }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "pv-%s-%s" .Release.Name .Values.tenantName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
  {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  mountOptions:
    {{- range .Values.persistentVolume.mountOptions }}
    - {{ . }}
    {{- end }}
  csi:
    driver: {{ .Values.persistentVolume.storageClassName }}
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#`and `/` are reserved for internal use and cannot be used in volumehandle
    volumeHandle: {{ .Values.persistentVolume.csi.volumeHandle }} # make sure this is unique in the cluster
    volumeAttributes:
      shareName: {{ .Values.persistentVolume.csi.volumeAttributes.shareName }} # name of Azure File Share
    nodeStageSecretRef:
      name: rabbitmq-storageaccount-secret
      namespace: {{ .Release.Namespace }}
{{- end }}
