{{- if .Values.persistentVolume.external }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "pv-%s-%s" .Release.Name .Values.tenantName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
  {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: {{ required "A storage class name is required" .Values.persistentVolume.storageClassName }}
  mountOptions:
    {{- range .Values.persistentVolume.mountOptions }}
    - {{ . }}
    {{- end }}
  csi:
    driver: {{ required "A storage class name is required" .Values.persistentVolume.csi.driver }}
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#`and `/` are reserved for internal use and cannot be used in volumehandle
    volumeHandle: KubeITSharedSVC-DEV-RG-WE#rabbitmqtenant2dev#rabbitmq # make sure this is unique in the cluster
    volumeAttributes:
      shareName: {{ .Values.persistentVolume.csi.volumeAttributes.shareName }} # name of Azure File Share
      storageAccount: rabbitmqtenant2dev  # name of Azure Storage Account
      resourceGroup: KubeITSharedSVC-DEV-RG-WE
      azureStorageIdentityClientID: 25dcb2d3-9838-4354-a0a4-63ac976e75fb
{{- end }}
