
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.tenantName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # autoEnableAllFeatureFlags: true
  replicas: {{ .Values.rabbitmqCluster.spec.replicas }}
  resources:
    requests:
      cpu: {{ .Values.rabbitmqCluster.spec.resources.requests.cpu }}
      memory: {{ .Values.rabbitmqCluster.spec.resources.requests.memory }}
    limits:
     memory: {{ .Values.rabbitmqCluster.spec.resources.limits.memory }}
  override:
    service:
      metadata:
        labels:
          {{- include "kubeit-rabbit-chart.selectorLabels" . | nindent 10 }}
{{- if .Values.persistentVolume.external }}
    statefulSet:
      spec:
        template:
          spec:
            securityContext:
              allowPrivilegeEscalation: false
              fsGroup: 999
              runAsUser: 999
              runAsGroup: 999
              privileged: false
              runAsNonRoot: true
              readOnlyRootFilesystem: true
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /var/lib/rabbitmq/mnesia/
                    name: {{ .Values.rabbitmqCluster.spec.containers.volumeMount.name }}
                securityContext:
                  capabilities:
                    drop:
                      - ALL

            initContainers:
              - name: setup-container
                securityContext:
                  capabilities:
                    drop:
                      - ALL
                volumeMounts:
                  - mountPath: /var/lib/rabbitmq/mnesia/
                    name: {{ .Values.rabbitmqCluster.spec.initContainers.volumeMount.name }}
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            spec:
              accessModes:
                {{- range .Values.persistentVolume.accessModes }}
                - {{ . }}
                {{- end }}
              storageClassName: {{ required "A storage class name is required" .Values.persistentVolume.storageClassName }}
              resources:
                requests:
                  storage: {{ .Values.persistentVolume.capacity.storage }}
            metadata:
              name: persistence-testmq
{{- end }}
  rabbitmq:
    additionalConfig: |
      {{ .Values.rabbitmqCluster.additionalConfig | nindent 6 }}
    {{- if .Values.rabbitmqCluster.advancedConfig }}
    advancedConfig: |
      {{ .Values.rabbitmqCluster.advancedConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.rabbitmqCluster.additionalPlugins }}
    additionalPlugins: |
    {{- range .Values.rabbitmqCluster.additionalPlugins }}
      - {{ . }}
    {{- end }}
    {{- end }}
  {{- if .Values.rabbitmqCluster.tls.enabled }}
  tls:
    secretName: {{ .Values.rabbitmqCluster.tls.secretName }}
  {{- end }}
  persistence:
    storage: {{ .Values.persistentVolume.capacity.storage }}
    storageClassName: {{ required "A storage class name is required" .Values.persistentVolume.storageClassName }}
  service:
    type: {{ .Values.service.type }}
