{{- if .Values.secretStore.create }}
{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}
apiVersion: external-secrets.io/v1
{{- else }}
apiVersion: external-secrets.io/v1beta1
{{- end }}
kind: SecretStore
metadata:
  name: {{ include "kubeit-rabbit-chart.fullname" . }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.secretStore.vaultUrl | lower }}
      serviceAccountRef:
        name: {{ include "kubeit-rabbit-chart.serviceAccountName" . }}
{{- end }}
