{{- range .Values.users }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: {{ .name }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" $ | nindent 4 }}
  annotations:
    reconcile-trigger: "true"
spec:
  tags:
  {{- range .tags }}
  - {{ . }}
  {{- end }}
  rabbitmqClusterReference:
    name: {{ printf "%s-%s" $.Release.Name $.Values.tenantName | trunc 63 | trimSuffix "-" }}
  importCredentialsSecret:
    name: {{ .userK8sSecretName }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbit-{{ .name }}-permission
spec:
  vhost: {{ .vhost | quote }}
  userReference:
    name: {{ .name | quote }}
  permissions:
    {{- range $key, $value := .permissions }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  rabbitmqClusterReference:
    name: {{ printf "%s-%s" $.Release.Name $.Values.tenantName | trunc 63 | trimSuffix "-" }}
---
{{- end }}
