{{- if .Values.virtualService.create }}
{{- $useGateway := "istio-system/global-internaluse-gateway" -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kubeit-rabbit-chart.fullname" . }}-ui
spec:
  gateways:
  - {{ $useGateway }}
  hosts:
  {{- if .Values.virtualService.host }}
  - {{ .Values.virtualService.host }}
  {{- else }}
  - {{ include "internaldns.host" . }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ printf "%s-%s" .Release.Name .Values.tenantName }}
        port:
          number: {{ .Values.service.uiPort }}
    timeout: 10s
    retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: "503,reset"
    {{- if .Values.virtualService.useCors }}
    corsPolicy:
      allowOrigins:
        {{- range $k,$v := .Values.virtualService.allowOrigins }}
        - exact: {{ $v }}
        {{- end }}
      allowMethods:
      - POST
      - GET
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - Content-Type
      - Authorization
      - Accept
      exposeHeaders:
      - Authorization
      - Content-Type
      - X-Custom-Header
      maxAge: "24h"
    {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kubeit-rabbit-chart.fullname" . | trunc 55 | trimSuffix "-" }}-tcp
spec:
  gateways:
  - {{ $useGateway }}
  hosts:
  {{- if .Values.virtualService.host }}
  - {{ .Values.virtualService.host }}
  {{- else }}
  - {{ include "internaldns.host" . }}
  {{- end }}
  tcp:
  - match:
    - port: {{ .Values.service.tcpPort }}
    route:
    - destination:
        host: {{ printf "%s-%s" .Release.Name .Values.tenantName }}
        port:
          number: {{ .Values.service.tcpPort }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kubeit-rabbit-chart.fullname" . | trunc 55 | trimSuffix "-" }}-amqps
spec:
  gateways:
  - {{ $useGateway }}
  hosts:
  {{- if .Values.virtualService.host }}
  - {{ .Values.virtualService.host }}
  {{- else }}
  - {{ include "internaldns.host" . }}
  {{- end }}
  tls:
  - match:
    - port: {{ .Values.service.amqpsPort }}
      sniHosts:
      {{- if .Values.virtualService.host }}
      - {{ .Values.virtualService.host }}
      {{- else }}
      - {{ include "internaldns.host" . }}
      {{- end }}
    route:
    - destination:
        host: {{ printf "%s-%s" .Release.Name .Values.tenantName }}
        port:
          number: {{ .Values.service.amqpsPort }}
{{- end }}
