{{- if .Values.virtualService.create }}
{{- $useGateway := "istio-system/global-internaluse-gateway" -}}
{{- $useDomain := .Values.internalDnsDomain -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kubeit-rabbit-chart.fullname" . }}-vs
spec:
  gateways:
  - {{ $useGateway }}
  hosts:
  {{- if .Values.virtualService.host }}
  - {{ .Values.virtualService.host }}
  {{- else }}
  - {{ printf "rabbitmq-%s-%s.%s.%s.%s.%s" .Values.tenantName .Release.Name .Values.clusterColour .Values.shortRegion .Values.env $useDomain }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ printf "%s-%s" .Release.Name .Values.tenantName }}
        port:
          number: {{ .Values.service.uiPort }}
    {{- if .Values.virtualService.useCors }}
    corsPolicy:
      allowOrigins:
        {{- range $k,$v := .Values.virtualService.allowOrigins }}
        - exact: {{ $v }}
        {{- end }}
      allowMethods:
      - POST
      - GET
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - Content-Type
      - Authorization
      - Accept
      exposeHeaders:
      - Authorization
      - Content-Type
      - X-Custom-Header
      maxAge: "24h"
    {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kubeit-rabbit-chart.fullname" . | trunc 55 | trimSuffix "-" }}-vs-tcp
spec:
  gateways:
  - {{ $useGateway }}
  hosts:
  {{- if .Values.virtualService.host }}
  - {{ .Values.virtualService.host }}
  {{- else }}
  - {{ printf "rabbitmq-%s-%s.%s.%s.%s.%s" .Values.tenantName .Release.Name .Values.clusterColour .Values.shortRegion .Values.env $useDomain }}
  {{- end }}
  tcp:
  - match:
    - port: {{ .Values.service.tcpPort }}
    route:
    - destination:
        host: {{ printf "%s-%s" .Release.Name .Values.tenantName }}
        port:
          number: {{ .Values.service.tcpPort }}
---
{{- end }}
