
debugEnvoyFilters: true
skipFilters: false

platform-service:
  app: session-manager
  image:
    containerPort: 8000
    repository: "kubeitglobalsvcauxacrwe.azurecr.io/test/sessionmanager"
    tag: "master-20240229.1"

  service:
    liveness:
      enabled: true

  defaultRouting:
    enabled: true
    rewriteUrlPrefix:
      enabled: false
    urlPrefixes:
      - session
    allHosts: false
    retries:
      enabled: true
      settings:
        attempts: 3
        perTryTimeout: 15s

  requestAuthentication:
    enabled: false

  authorizationPolicy:
    enabled: false

  resources:
    requests:
      cpu: 10m
      memory: 256M

  env:
    ASPNETCORE_URLS: http://*:8000
    REDIS_PORT: 6379
    LOGIN_LANDING_URL: "/"

    REDIS_HOST: session-manager-redis-master
    REDIS_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: session-manager-redis
          key: redis-password

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1654
    runAsGroup: 1654
    capabilities:
      drop:
        - ALL

redis:
  enabled: true
  global:
    imageRegistry: kubeitglobalsvcauxacrwe.azurecr.io
  architecture: standalone

  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    containerSecurityContext:
      readOnlyRootFilesystem: true

  replica:
    persistence:
      enabled: false

  commonConfiguration: |-
    appendonly yes
    save ""
    loglevel verbose
