{{- if .Values.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.app }}-config-map
  labels:
    app.kubernetes.io/name: {{ include "platform-service.name" . }}
    helm.sh/chart: {{ include "platform-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ required "app is required" .Values.app | trunc 63 | trimSuffix "-" }}
{{ include "kubeit.tags" . | trim | indent 4 }}
data:
{{ tpl .Values.configMap.data $ | indent 2 }}
{{- end }}
