{{- if .Values.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "services-chart.configMapName" . }}
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
data:
{{ tpl .Values.configMap.data $ | indent 2 }}
{{- end }}
