{{- if .Values.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.app }}-config-map
  labels:
{{ include "appLabels" . | trim | indent 4 }}
data:
{{ tpl .Values.configMap.data $ | indent 2 }}
{{- end }}
