---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "services-chart.fullname" . }}
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "services-chart.selectorLabels" . | nindent 6 }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "services-chart.labels" . | nindent 8 }}
        {{- with .Values.additionalPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.sessionManager.deploy }}
        session-management: backend
        session-manager-name: {{ .Values.sessionManager.name | trunc 63 | trimSuffix "-" }}
        {{- end }}
        {{- if .Values.sessionManager.use }}
        session-management: frontend
        authn-redirect: enabled
        session-manager-name: {{ .Values.sessionManager.name | trunc 63 | trimSuffix "-" }}
        {{- end }}
      {{- if or (.Values.additionalPodAnnotations) (.Values.tracing.enabled) }}
      annotations:
      {{- with .Values.additionalPodAnnotations}}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tracing.enabled }}
        proxy.istio.io/config: |
          tracing:
            sampling: {{ .Values.tracing.sampling }}
            zipkin:
              address: collector.{{ .Values.kubeit.managementNamespace }}.svc.cluster.local:9411
      {{- end }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "services-chart.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ include "services-chart.name" . }}
          image: {{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 10 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 10 }}
          {{- end }}
          {{- if .Values.envs }}
          env:
            {{- range .Values.envs }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.envsFrom }}
            {{- toYaml .Values.envsFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.additionalEnvsFrom }}
            {{- toYaml .Values.additionalEnvsFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.sessionManager.deploy }}
            - name: SESSION_MANAGER_ID
              value: {{ .Values.sessionManager.name | replace "-" "" | quote }}
          {{- end }}
          {{- if .Values.health.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.health.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.health.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.health.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.health.startupProbe }}
          startupProbe:
            {{- toYaml .Values.health.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if and (.Values.resizePolicy) (semverCompare ">=1.33.0" .Capabilities.KubeVersion.Version) }}
          resizePolicy:
            {{- toYaml .Values.resizePolicy | nindent 12 }}
          {{- end }}
        {{- if .Values.additionalContainers }}
          {{- toYaml .Values.additionalContainers | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
