---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "services-chart.fullname" . }}
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "services-chart.selectorLabels" . | nindent 6 }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 6 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "services-chart.labels" . | nindent 8 }}
        {{- with .Values.additionalPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.additionalPodAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "services-chart.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ include "services-chart.name" . }}
          image: {{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: tcp
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.args }}
            {{- toYaml .Values.args | nindent 10 }}
          {{- end }}
          {{- if .Values.envs }}
          env:
            {{- toYaml .Values.envs | nindent 12 }}
          {{- end }}
          {{- if .Values.envsFrom }}
          envFrom:
            {{- toYaml .Values.envsFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.health.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.health.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.health.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.health.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.health.startupProbe }}
          startupProbe:
            {{- toYaml .Values.health.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.valumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
        {{- if .Values.additionalContainers }}
          {{- toYaml .Values.additionalContainers | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
