{{- if .Values.defaultRouting.enabled}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "platform-service.fullname" . | trunc 54 }}-destrule
  labels:
    app: {{ required "app is required" .Values.app | trunc 63 | trimSuffix "-" }}
{{ include "kubeit.tags" . | trim | indent 4 }}
spec:
  host: {{ include "platform-service.fullQualifiedServiceName" . }}
  trafficPolicy:
    loadBalancer:
      {{- if eq .Values.defaultRouting.loadBalancerPolicy "STICKY_SESSIONS"}}
      consistentHash:
        httpCookie:
          name: onegateway_sessid
          ttl: 0s
      {{- else }}
      simple: {{ default "RANDOM" .Values.defaultRouting.loadBalancerPolicy }}
      {{- end}}
    tls:
      mode: {{ .Values.defaultRouting.tls.mode }}
{{- end}}
