{{- if and (.Values.defaultRouting.enabled) (.Values.destinationRule.enabled) }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ include "services-chart.fullname" . }}-dr
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  host: {{ include "services-chart.fullFQDN" . }}
  trafficPolicy:
    loadBalancer:
      {{- if eq .Values.destinationRule.loadBalancerPolicy "STICKY_SESSIONS" }}
      consistentHash:
        httpCookie:
          name: onegateway_sessid
          ttl: 0s
      {{- else }}
      simple: {{ default "RANDOM" .Values.destinationRule.loadBalancerPolicy }}
      {{- end }}
    tls:
      {{- toYaml .Values.destinationRule.tls | nindent 6 }}
{{- end }}
