{{- if and (.Values.secretStore.enabled) (.Values.serviceAccount.enabled) }}
{{ range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name | trunc 63 | trimSuffix "-" | lower }}
  labels:
    {{- include "services-chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "services-chart.fullname" $ }}
    kind: SecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
    {{- range .refs }}
    - secretKey: {{ .keyName }}
      remoteRef:
        key: {{ .kvSecretName }}
    {{- end }}
{{- end }}
{{- end }}
