{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "platform-service.fullname" . }}-hpa
  labels:
{{ include "appLabels" . | trim | indent 4 }}
spec:
  maxReplicas: {{.Values.hpa.maxReplicas}}
  minReplicas: {{.Values.hpa.minReplicas}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "platform-service.fullname" . }}
  targetCPUUtilizationPercentage: 80
{{- end }}
