{{- if and (.Values.networkPolicy.enabled) (.Values.networkPolicy.appsAllowedAccess) -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "services-chart.fullname" . }}-np
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "services-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
{{- range .Values.networkPolicy.appsAllowedAccess }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .namespace }}
      podSelector:
        matchLabels:
          {{- toYaml .labels | nindent 10 }}
{{- end }}
{{- end }}
