{{- if .Values.networkPolicy.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "services-chart.fullname" . }}-np
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "services-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            istio: pilot
        namespaceSelector:
          matchLabels:
            istio-operator-managed: Reconcile
{{- if .Values.destinationRule.enabled }}
    - from:
      - podSelector:
          matchLabels:
            istio: ingressgateway
        namespaceSelector:
          matchLabels:
            istio-operator-managed: Reconcile
{{- end }}
{{- range .Values.networkPolicy.appsAllowedAccess }}
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ . }}
      ports:
      - protocol: TCP
        port: {{ $.Values.service.containerPort }}
{{- end }}
{{- end }}
