---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ $.Values.app }}-secret-store"
spec:
  provider:
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: {{ $.Values.keyVaultSecrets.tenantId }}
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: {{ $.Values.keyVaultSecrets.vaultUrl }}
{{- range $keyVaults:= .Values.keyVaultSecrets.keyVaults }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $.Values.app }}-secret-definition"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ $.Values.app }}-secret-store"
    kind: SecretStore
  {{- range $secrets:= .secrets }}
  target:
    name: "{{ .k8sSecretName }}"
    creationPolicy: Owner
  {{- end }}
  data:
  {{- range $secrets:= .secrets }}
  - secretKey: {{ .k8sSecretKey }}
    remoteRef:
      key: "{{ .keyVaultSecretName }}"
  {{- end }}
{{- end }}
