{{- if and (.Values.secretStore.enabled) (.Values.serviceAccount.enabled) }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "services-chart.fullname" . }}
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.secretStore.vaultUrl | lower }}
      serviceAccountRef:
        name: {{ include "services-chart.serviceAccountName" . }}
{{- end }}
