{{/*
Create the name of the service account to use
*/}}
{{- define "platform-service.serviceAccountName" -}}
{{- if .Values.serviceAccount.useReleasePrefix -}}
    {{- .Release.Name -}}-
{{- end -}}
{{- if .Values.serviceAccount.create -}}
    {{ default .Values.app .Values.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.serviceAccount.name }}
{{- end -}}
{{- end -}}
{{- if not .Values.deploymentOnly -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
{{- if $.Values.workloadIdentity }}
    azure.workload.identity/client-id: 9bfd1fa5-c5c8-4b89-99a7-e11b9a7bc426
    azure.workload.identity/tenant-id: adf10e2b-b6e9-41d6-be2f-c12bb566019c
{{- end }}
  name: {{ include "platform-service.serviceAccountName" . }}
  labels:
{{ include "appLabels" . | trim | indent 4 }}
{{- end}}
{{- end}}
