---
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "services-chart.fullname" . }}
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
  {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "services-chart.selectorLabels" . | nindent 4 }}
{{- end }}