{{- if .Values.defaultRouting.enabled -}}
{{- range $host := $.Values.defaultRouting.hosts }}
{{- if eq $host "auto" -}}
{{- $host = include "services-chart.autoFQDNexternal" $ -}}
{{- end }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $host  | replace "." "-" | trimSuffix "-" | trunc 59 }}-ext
  labels:
    {{- include "services-chart.labels" $ | nindent 4 }}
spec:
  hosts:
    - {{ $host }}
  gateways:
    - {{ $.Values.gateway.name | trim }}
{{ include "services-chart.virtualserviceContent" $ | indent 2 }}
{{- end }}
---
{{- range $host := $.Values.defaultRouting.internalHosts }}
{{- if eq $host "auto" -}}
{{- $host = include "services-chart.autoFQDNinternal" $ -}}
{{- end }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $host  | replace "." "-" | trimSuffix "-" | trunc 59 }}-int
  labels:
    {{- include "services-chart.labels" $ | nindent 4 }}
spec:
  hosts:
    - {{ $host }}
  gateways:
    - {{ $.Values.gateway.internalName | trim }}
{{ include "services-chart.virtualserviceContent" $ | indent 2 }}
{{- end }}
---
{{- if $.Values.destinationRule.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "services-chart.fullname" $ }}-mesh
spec:
  hosts:
    - {{ include "services-chart.fullFQDN" $ }}
  gateways:
    - mesh
  http:
    - route:
      - destination:
          host: {{ include "services-chart.fullFQDN" $ }}
{{- if $.Values.defaultRouting.retries }}
      retries:
        {{- toYaml $.Values.defaultRouting.retries | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}
