{{- define "retries" -}}
{{- if .Values.defaultRouting.retries.enabled }}
    retries:
{{- if .Values.defaultRouting.retries.settings }}
{{ .Values.defaultRouting.retries.settings | toYaml | trim | indent 6 }}
{{- else }}
      attempts: 3
      perTryTimeout: 2s
{{- end -}}
{{- end -}}
{{- end -}}

{{- if not .Values.deploymentOnly -}}
{{- if .Values.defaultRouting.enabled}}
{{- $fullName := include "platform-service.fullname" . -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "platform-service.serviceName" . }}
spec:
  hosts:
  - {{ include "platform-service.fullQualifiedServiceName" . }}
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: {{ include "platform-service.fullQualifiedServiceName" . | quote }}
{{- include "retries" . }}

---
{{- if .Values.gateway.exposeService }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "platform-service.serviceName" . }}-external
  labels:
{{ include "appLabels" . | trim | indent 4 }}
spec:
  hosts:
  {{- if .Values.defaultRouting.kubeitDefaultHosts.enabled }}
  {{ $tenantPrefix := "" }}
  {{- if and $.Values.defaultRouting.kubeitDefaultHosts.enabled $.Values.defaultRouting.kubeitDefaultHosts.tenantPrefixEnabled }}
  {{ $tenantPrefix = printf "-%s" .Values.kubeit.tenantName }}
  {{- end }}
    - "{{ .Values.defaultRouting.kubeitDefaultHosts.hostsPrefix | default .Values.app }}{{ $tenantPrefix }}.{{ .Values.kubeit.clusterSubdomain }}.{{ .Values.defaultRouting.kubeitDefaultHosts.dnsDomain }}"                                                                      # Cluster specific subdomain, i.e.: dev001
    - "{{ .Values.defaultRouting.kubeitDefaultHosts.hostsPrefix | default .Values.app }}{{ $tenantPrefix }}.{{ .Values.kubeit.shortRegion }}.{{ .Values.kubeit.environmentName }}.{{ .Values.defaultRouting.kubeitDefaultHosts.dnsDomain }}"                                      # F5/Active Cluster
    - "{{ .Values.defaultRouting.kubeitDefaultHosts.hostsPrefix | default .Values.app }}{{ $tenantPrefix }}.{{ .Values.kubeit.clusterColour }}.{{ .Values.kubeit.shortRegion }}.{{ .Values.kubeit.environmentName }}.{{ .Values.defaultRouting.kubeitDefaultHosts.dnsDomain }}"   # Colour cluster - blue/green deployment
  {{- if .Values.defaultRouting.kubeitDefaultHosts.tenantMultiRegion }}
    - "{{ .Values.defaultRouting.kubeitDefaultHosts.hostsPrefix | default .Values.app }}{{ $tenantPrefix }}.{{ $.Values.kubeit.environmentName }}.{{ .Values.defaultRouting.kubeitDefaultHosts.dnsDomain }}"                                                                                                              # Traffic Manager
  {{- end }}
  {{- end }}
  {{- range .Values.defaultRouting.hosts }}
    - {{ . | quote }}
{{- end }}
  gateways:
    - {{ required "A valid .Values.gateway.name entry required!" .Values.gateway.name }}
{{- $prefixes := default (list .Values.app) .Values.defaultRouting.urlPrefixes }}
  http:
{{- if .Values.defaultRouting.urlExactMatches }}
  - match:
  {{- range .Values.defaultRouting.urlExactMatches }}
  {{- if hasPrefix "/" . }}
    {{ fail "url matches must not include leading slash"}}
  {{- end}}
  {{- $slashMatch := printf "/%s" . }}
    - uri:
        exact: {{ $slashMatch }}
    - uri:
        prefix: {{ $slashMatch }}/
  {{- end }}
  # routes to service
    route:
    - destination:
        host: {{ include "platform-service.fullQualifiedServiceName" . | quote }}
{{- if .Values.defaultRouting.corsPolicy }}
    corsPolicy:
{{ .Values.defaultRouting.corsPolicy | toYaml | trim | indent 6 }}
{{- end }}
{{- end }}

{{- if .Values.defaultRouting.redirectOnNoTrailingSlash }}
  # redirect on prefixes without trailing slashes
  {{- range $prefixes }}
  {{- $slashPrefix := printf "/%s" . }}
  - match:
    - uri:
        exact: {{ $slashPrefix }}
    redirect:
      uri: {{ $slashPrefix }}/
  {{- end}}
{{- end}}
  # routes to service
  - route:
    - destination:
        host: {{ include "platform-service.fullQualifiedServiceName" . | quote }}
{{- if .Values.defaultRouting.corsPolicy }}
    corsPolicy:
{{ .Values.defaultRouting.corsPolicy | toYaml | trim | indent 6 }}
{{- end -}}

  {{- if not .Values.defaultRouting.catchAll }}
    match:
    {{- range $prefixes }}
    {{- if hasPrefix "/" . }}
      {{ fail "url prefixes must not include leading slash"}}
    {{- end}}
    {{- $slashPrefix := printf "/%s" . }}
    - uri:
        prefix: {{ $slashPrefix }}/
    {{- end }}
  {{- end }}
{{- if .Values.defaultRouting.rewriteUrlPrefix.enabled }}
    rewrite:
      uri: {{ required "rewriteUri is required" .Values.defaultRouting.rewriteUrlPrefix.replaceWith }}
{{- end}}
    # deprecated
    headers:
      request:
        add:
          x-appname: {{ first $prefixes }}
{{- include "retries" . }}
{{- end}}
{{- end}}
{{- end}}
