# Reference ArgoCD application definition - https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
{{- range $app := .Values.applications }}
{{- range $environment := $app.environments }}
{{- range $environment.namespaces }}

{{- if eq $.Values.env $environment.name }}
{{- if has $.Values.region $environment.region }}
{{- if has $.Values.clusterColour $environment.clusterColour }}
{{- if not ( and ( contains "kubenet" $.Values.networkPlugin ) ( contains "windows" $app.containerOS ) ) }}

# https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops
{{- $envDirectory := "" }}
{{- if eq $.Values.env "aux" }}
{{ $envDirectory = "auxiliary" }}
{{- else }}
{{ $envDirectory = $.Values.env }}
{{- end }}

# ArgoCD Image Updater Values Loader
{{- $globalScope := printf "appValues/%s/appGlobal.yaml" $app.name }}
{{- $envScope := printf "appValues/%s/environment/%s/%s.yaml" $app.name $envDirectory $envDirectory }}
{{- $regionScope := printf "appValues/%s/environment/%s/region/%s/%s.yaml" $app.name $envDirectory $.Values.region $.Values.region }}
{{- $clusterScope := printf "appValues/%s/environment/%s/region/%s/cluster/%s.yaml" $app.name $envDirectory $.Values.region $.Values.clusterColour }}
{{- $valuesList := list $globalScope $envScope $regionScope $clusterScope }}
# ArgoCD Image Updater Variables
{{- $enableUpdater := "" }}
{{- $updaterRepo := "" }}
{{- $updaterConstraint := "" }}
{{- $updaterStrategy := "" }}
{{- $updaterPullSecret := "" }}
{{- $updaterAllowTags := "" }}
{{- $updaterIgnoreTags := "" }}
{{- $updaterGitBranch := "" }}
{{- $updaterGitSecret := "" }}
# ArgoCD Image Updater Logic
{{ range $valuesList }}
{{ range $.Files.Lines . }}
{{- if eq (contains "argoCDImageUpdater" . ) true }}
{{ $enableUpdater = true }}
{{- else if eq (contains "updaterRepository" . ) true }}
{{ $updaterRepo = "" | regexReplaceAll "\"" . | replace "updaterRepository:" "" | trim }}
{{- else if eq (contains "updaterVersionConstraint" .) true }}
{{ $updaterConstraint = "" | regexReplaceAll "\"" . | replace "updaterVersionConstraint:" "" | trim }}
{{- else if eq (contains "updaterAllowTags" .) true }}
{{ $updaterAllowTags = "" | regexReplaceAll "\"" . | replace "updaterAllowTags:" "" | trim }}
{{- else if eq (contains "updaterIgnoreTags" .) true }}
{{ $updaterIgnoreTags = . | replace "updaterIgnoreTags:" "" | trim }}
{{- else if eq (contains "updaterGitBranch" .) true }}
{{ $updaterGitBranch = "" | regexReplaceAll "\"" . | replace "updaterGitBranch:" "" | trim }}
{{- else if eq (contains "gitSecretName" .) true }}
{{ $updaterGitSecret = "" | regexReplaceAll "\"" . | replace "gitSecretName:" "" | trim }}
{{- else if eq (contains "updaterStrategy" .) true }}
{{ $updaterStrategy = "" | regexReplaceAll "\"" . | replace "updaterStrategy:" "" | trim }}
{{- else if eq (contains "updaterPullSecret" .) true }}
{{ $updaterPullSecret = "" | regexReplaceAll "\"" . | replace "updaterPullSecret:" "" | trim }}
{{- else if eq (contains "updaterGitSecret" .) true }}
{{ $updaterGitSecret = "" | regexReplaceAll "\"" . | replace "updaterGitSecret:" "" | trim }}
{{- end }}
{{- end }}
{{- end }}
{{- $appTruncName := printf "%s-%s" ($app.name | trunc 31 | trimSuffix "-") $.Values.clusterSubdomain | trunc 43 | trimSuffix "-" -}}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appTruncName }}
  namespace: {{ $.Values.managementNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $app.syncWave | default "'1'" }}
    {{- if $enableUpdater }}
    argocd-image-updater.argoproj.io/write-back-method: {{ if $updaterGitSecret }}{{ toYaml ( printf "git:secret:%s" $updaterGitSecret ) }}{{- else -}}{{ default "git:repocreds" }}{{- end }}
    argocd-image-updater.argoproj.io/git-branch: {{ $updaterGitBranch | default $.Values.targetRevision }}
    argocd-image-updater.argoproj.io/image-list: {{ if $updaterConstraint }}{{  toYaml (printf "alias=%s:%s" $updaterRepo $updaterConstraint) }}{{- else -}}{{ $updaterRepo }}{{- end }}
    argocd-image-updater.argoproj.io/alias.allow-tags: {{ if $updaterAllowTags }}{{ toYaml (printf "regexp:%s" $updaterAllowTags) }}{{- else -}}{{ default "any" }}{{- end }}
    argocd-image-updater.argoproj.io/alias.ignore-tags: {{ $updaterIgnoreTags | default "none" }}
    argocd-image-updater.argoproj.io/alias.update-strategy: {{ $updaterStrategy | default "semver" }}
    {{- if $updaterPullSecret }}
    argocd-image-updater.argoproj.io/alias.pull-secret: {{ $updaterPullSecret }}
    {{- end }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "{{ . }}"
    server: 'https://kubernetes.default.svc'
  project: "{{ $.Values.tenantName }}"
  source:
    repoURL: "{{ ($app.chart | default dict ).repoURL | default $.Values.repoURL }}"
    {{- if and (hasKey ($app.chart | default dict) "targetRevision") (eq ($app.chart | default dict ).targetRevision "latest") }}
    {{- else }}
    targetRevision: "{{ ($app.chart | default dict ).targetRevision | default $.Values.targetRevision }}"
    {{- end }}
    {{- if hasKey ($app.chart | default dict) "name" }}
    chart: "{{ $app.chart.name }}"
    {{- else }}
    path: "{{ ($app.chart | default dict ).path | default $.Values.globals.chart.path }}"
    {{- end }}
    helm:
      ignoreMissingValueFiles: {{ ($app.chart | default dict ).ignoreMissingValueFiles | default $.Values.globals.chart.ignoreMissingValueFiles }}
      skipCrds: {{ ($app.chart | default dict ).skipCrds | default $.Values.globals.chart.skipCrds }}
      valueFiles:
        - ../../../chart/appValues/global.yaml
        - ../../../chart/appValues/{{ $app.name }}/appGlobal.yaml
        - ../../../chart/appValues/{{ $app.name }}/environment/{{ $envDirectory }}/{{ $envDirectory }}.yaml
        - ../../../chart/appValues/{{ $app.name }}/environment/{{ $envDirectory }}/region/{{ $.Values.region }}/{{ $.Values.region }}.yaml
        - ../../../chart/appValues/{{ $app.name }}/environment/{{ $envDirectory }}/region/{{ $.Values.region }}/cluster/{{ $.Values.clusterColour }}.yaml
        - ../../../chart/appValues/{{ $app.name }}/environment/{{ $envDirectory }}/region/{{ $.Values.region }}/cluster/namespaces/{{ . }}.yaml
      values: |
        app: {{ $app.name }}
        namespace: {{ . }}
        gateway:
          name: istio-system/global-https-{{ $.Values.ingressType }}-default-gateway
        defaultRouting:
          kubeitDefaultHosts:
            dnsDomain: "{{ $.Values.dnsDomain }}"
            tenantMultiRegion: "{{ $.Values.tenantMultiRegion }}"
        kubeit:
          region: "{{ $.Values.region }}"
          namespace: "{{ . }}"
          clusterSubdomain: "{{ $.Values.clusterSubdomain }}"
          clusterColour: "{{ $.Values.clusterColour }}"
          ingressType: "{{ $.Values.ingressType }}"
          shortRegion: "{{ $.Values.shortRegion }}"
          tenantName: "{{ $.Values.tenantName }}"
          environmentName: "{{ $.Values.env }}"
          tenantPodIdentityName: "{{ $.Values.tenantPodIdentityName }}"
  {{- if ($app.ignoreReplicasOnSync | default false) }}
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: {{ $app.selfHeal | default "true" }}
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=false
      {{if ($app.ignoreReplicasOnSync | default false) }}- RespectIgnoreDifferences{{ end }}
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
