{{- range $team := .Values.global.teams -}}
{{- $teamName := $team.name -}}
{{- range $tenantEnv := $team.envs -}}
{{- $logicalEnvName := $tenantEnv.name -}}
{{- if hasKey $tenantEnv "targetCluster" -}}
{{- if hasKey $tenantEnv.targetCluster "env" -}}
{{- if hasKey $tenantEnv.targetCluster "region" -}}
{{- if hasKey $tenantEnv.targetCluster "colour" -}}
{{- if eq $tenantEnv.targetCluster.env $.Values.global.env -}}
{{- if eq $tenantEnv.targetCluster.region $.Values.global.shortRegion -}}
{{- if eq $tenantEnv.targetCluster.colour $.Values.global.clusterColour -}}
{{- $appName := printf "%s-%s-%s" $.Values.global.tenantName $teamName $logicalEnvName | trunc 63 | trimSuffix "-" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ $.Values.global.managementNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "{{ $.Values.global.tenantName }}"
  destination:
    namespace: {{ $.Values.global.managementNamespace }}
    server: https://kubernetes.default.svc
  sources:
    - repoURL: {{ $.Values.global.appLogicalEnvChart.repoURL }}
      chart: {{ $.Values.global.appLogicalEnvChart.chart }}
      targetRevision: {{ $.Values.global.appLogicalEnvChart.targetRevision }}
      helm:
        valueFiles:
         - $values/envs/{{ $teamName }}/{{ $logicalEnvName }}.yaml
        ignoreMissingValueFiles: true
        values: |
          env: {{ $.Values.global.env }}
          region: {{ $.Values.global.region }}
          dnsDomain: {{ $.Values.global.dnsDomain }}
          internalDnsDomain: {{ $.Values.global.internalDnsDomain }}
          clusterSubdomain: {{ $.Values.global.clusterSubdomain }}
          clusterColour: {{ $.Values.global.clusterColour }}
          ingressType: {{ $.Values.global.ingressType }}
          shortRegion: {{ $.Values.global.shortRegion }}
          tenantName: {{ $.Values.global.tenantName }}
          targetRevision: {{ $.Values.global.targetRevision }}
          repoURL: {{ $.Values.global.repoURL }}
          managementNamespace: {{ $.Values.global.managementNamespace }}
          logicalEnvName: {{ $logicalEnvName }}
          teamName: {{ $teamName }}
    - repoURL: {{ $.Values.global.repoURL }}
      targetRevision: {{ $.Values.global.targetRevision }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
      limit: 2
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=false
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
