{{- if .Values.sessionManager.deploy }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: session-frontend-filter-{{ .Values.app }}
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      session-management: frontend
      session-manager-name: {{ .Values.sessionManager.sessionManagerName | trunc 63 | trimSuffix "-" }}
  configPatches:
  # adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.jwt_authn"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.session-frontend-filter-{{ .Values.app }}
{{- include "filter.lua" (dict "namespace" .Release.Namespace "redirect" true "debugEnvoyFilters" .Values.sessionManager.debugEnvoyFilters ) | nindent 8 }}
{{- end }}
