{{- if .Values.sessionManagerDeployment }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: session-backend-filter-{{ .Values.app }}
spec:
  workloadSelector:
    labels:
      session-management: backend
      session-manager-name: {{ .Values.app | trunc 63 | trimSuffix "-" }}
  configPatches:
    # adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.jwt_authn"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.filters.http.session-backend-filter-{{ .Values.app }}
{{- include "filter.lua" (dict "namespace" .Release.Namespace "redirect" false "debugEnvoyFilters" .Values.debugEnvoyFilters ) | nindent 8 }}
{{- end }}
