{{- if .Values.sessionManagerDeployment }}
---
apiVersion: v1
kind: Service
metadata:
  name: session-manager
  labels:
    {{- include "services-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "services-chart.selectorLabels" . | nindent 4 }}
{{- end }}
