{{- if .Values.sessionManagerDeployment }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: session-manager-{{ .Values.app }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
  - from:
    - source:
        namespaces:
        - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "services-chart.name" . }}
{{- end }}
