{{- if .Values.sessionManagerDeployment }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ printf "session-manager-%s"  .Values.app | trunc 63 | trimSuffix "-" }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
  - from:
    - source:
        namespaces:
        - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{ include "services-chart.selectorLabels" . | nindent 6 }}
{{- end }}
