{{- if eq .Values.azureKeyVaultSecrets.type "csi-keyvault" }}
{{- range $keyVault:= .Values.azureKeyVaultSecrets.azureKeyVaults }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .azureKeyVaultName | lower }}-secret-class
spec:
  provider: azure
  secretObjects:
  {{- range $secrets := .secrets }}
    - secretName: "{{ .k8sSecretName }}"
      type: Opaque
      data:
      {{- range $data := .data }}
        - objectName: {{ .azureKeyVaultSecretName }}
          key: {{ .k8sSecretKey }}
      {{- end }}
  {{- end }}
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ .azureKeyVaultName }}
    objects: |
      array:
  {{- range $secrets:= .secrets }}
    {{- range $data := .data }}
        - |
          objectName: "{{ .azureKeyVaultSecretName }}"
          objectType: secret
    {{- end }}
  {{- end }}
    tenantId: {{ $.Values.azureKeyVaultSecrets.tenantId }}
{{- end }}
{{- end }}
