{{- range $keyVault := .Values.azureKeyVaultSecrets.azureKeyVaults }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: # Input clientId of created Managed Identity
    azure.workload.identity/tenant-id: adf10e2b-b6e9-41d6-be2f-c12bb566019c
  name: "{{ .azureKeyVaultName | lower  }}-service-account"
{{- end }}
