---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
      app: kubeit-secrets
      chart: kubeit-secrets-chart
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
  annotations:
    azure.workload.identity/client-id: {{ $.Values.azureKeyVaultSecrets.clientId }}
    azure.workload.identity/tenant-id: {{ $.Values.azureKeyVaultSecrets.tenantId }}
  name: "{{ $.Release.Name | lower }}-service-account"
