{{ $platformService := index .Values "platform-service" }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
  - from:
    - source:
        namespaces:
        - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ $platformService.app }}
      version: {{ $platformService.version }}
