{{- range $host := $.Values.deploy.defaultRouting.hosts }}
{{ $namePostfix := $host | replace "." "-" }}
---
apiVersion: v1
kind: Service
metadata:
  name: sm-{{ $namePostfix }}
  labels:
    {{- include "sessionmanager-chart.labels" $ | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sessionmanager-chart.selectorLabels" $ | nindent 4 }}
{{- end }}
