{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "platform-service.fullname" . }}
  labels:
{{ include "appLabels" . | trim | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  action: ALLOW
  rules:
  {{- range .Values.authorizationPolicy.authorizedServices }}
  - from:
    - source:
      {{- if .servicePrincipalFullName }}
        {{- $fullSpName := .servicePrincipalFullName }}
        principals: [{{ .servicePrincipalFullName | quote }}]
      {{- else }}
        {{- $servicePrincipalName := required "servicePrincipalName is required" .servicePrincipalName }}
        {{- $namespace := default $.Release.Namespace .servicePrincipalNamespace }}
        {{- $fullSpName := printf "cluster.local/ns/%s/sa/%s" $namespace $servicePrincipalName | quote }}
        principals: [{{ $fullSpName }}]
      {{- end }}
      {{- /* workaround for default value not working with bool */ -}}
      {{- if or (.requireJwt) (eq (.requireJwt | toString) "<nil>") }}
        requestPrincipals: ["*"]
      {{- end }}
  {{- end }}
  - from:
    - source:
        namespaces: ["istio-system"]
        requestPrincipals: ["*"]
{{- end }}
