{{- if .Values.requestAuthentication.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "platform-service.fullname" . }}
  labels:
{{ include "appLabels" . | trim | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  jwtRules:
{{ .Values.requestAuthentication.jwtRules | toYaml | indent 2 }}
{{- end }}
