{{- if not .Values.deploymentOnly -}}
{{- if .Values.defaultRouting.enabled -}}
{{- $fullName := include "platform-service.fullname" . -}}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "platform-service.serviceName" . }}
spec:
  hosts:
  - {{ include "platform-service.fullQualifiedServiceName" . }}
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: {{ include "platform-service.fullQualifiedServiceName" . | quote }}
{{- include "retries" $ | indent 4 }}
---
{{- if .Values.gateway.exposeService -}}
{{- if gt (len .Values.defaultRouting.hosts) 0 -}}
{{- if .Values.defaultRouting.oneDomainPerVirtualService -}}
{{- range $host := $.Values.defaultRouting.hosts }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $host | replace "." "-" | trimSuffix "-" | trunc 59 }}-ext
  labels:
{{ include "appLabels" $ | trim | indent 4 }}
spec:
  hosts:
    - {{ $host }}
  gateways:
    - {{ required "A valid .Values.gateway.name entry required!" $.Values.gateway.name }}
{{- include "platform-service.virtualserviceContent" $ | indent 2 }}
---
{{- end }}
{{- else }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "platform-service.serviceName" . }}-external
  labels:
{{ include "appLabels" . | trim | indent 4 }}
spec:
  hosts:
{{- range .Values.defaultRouting.hosts }}
    - {{ . | quote }}
{{- end }}
  gateways:
    - {{ required "A valid .Values.gateway.name entry required!" $.Values.gateway.name }}
{{- include "platform-service.virtualserviceContent" $ | indent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
