---
name: Lint and Test Charts

on: pull_request  # yamllint disable-line rule:truthy

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.11.3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

#      - name: Update dependencies for each chart
#        run: |
#          for chart in charts/*; do
#            if [ -f "$chart/Chart.yaml" ]; then
#              echo "Updating dependencies for $chart"
#              helm dependency update "$chart"
#            fi
#         done

      - uses: pre-commit/action@v3.0.1

      - name: Run helm tests
        run: python run-tests.py
