---
# app-in-logical-env chart to use to generate application within one logical env
appLogicalEnvChart:
  repoURL: https://github.com/dnv-gssit/kubeit-charts.git
  path: kubeit-apps-in-env
  targetRevision: test-server-side-apply
