{{- range .Values.queue }}
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ printf "%s-queue" .name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kubeit-rabbit-chart.labels" $ | nindent 4 }}
spec:
  name: {{ .name }}
  arguments:
    x-max-length-bytes: {{ .arguments.x_max_length_bytes }} ## setting the retention policy
    x-message-ttl: {{ .arguments.x_message_ttl }} ## setting the message TTL
  autoDelete: true # queue that has had at least one consumer is deleted when last consumer unsubscribes
  durable: true # the queue will survive a broker restart
  rabbitmqClusterReference:
    name: {{ printf "%s-%s" $.Release.Name $.Values.tenantName | trunc 63 | trimSuffix "-" }}
{{- end }}
