---
globals:
  chart:
    # repoURL: "https://dnv-gssit.github.io/kubeit-charts/"
    # name: kubeit-deployment-chart
    # targetRevision: 1.0.13
    repoURL: "https://github.com/dnv-gssit/kubeit-charts.git"
    path: charts/kubeit-deployment-chart
    targetRevision: feature/migration_kubeit
    ignoreMissingValueFiles: true
    skipCrds: true

applications:
  # - name: ""                          # Required: tenant_app_name - name of the app, must be the same as folder name in appValues directory
  #   namespace: ""                     # Required: tenant_namespace - name of the namespace provided during KubeIT onboarding process
  #   containerOS: ""                   # Required: linux, windows - define container OS to deploy on supported network plugin
  #   environments: []                  # Required: List of the environments with parameters for controlling where apps will be deployed
  #     name: []                        # Required: aux, nonprod, prod - on which environments application will be deployed
  #     region: []                      # Required: westeurope, eastus2 - on which regions application will be deployed
  #     clusterColour: []               # Required: blue, green - on which clusters application will be deployed
  #     namespaces: []                  # Required: one of the values provided to the cluster administration team during bootstrapping, namespace(s) where the application is going to be deployed
  #   syncWave: "1"                     # Optional - if applications need to be deployed in specific order you can specify in which wave, more info: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
  #   selfHeal: false                   # Optional - set to false if you want ArgoCD to not override your manual changes on the cluster, true by default
  #   chart:                            # Optional - if application will not be deployed using provided kubeit-deployment-chart
  #     repoURL: ""                     # Optional - helm repo url
  #     name: ""                        # Optional - name of the helm chart in helm repo, if repoURL is pointing on git repo please don't provide chart name
  #     targetRevision: ""              # Optional - version of the chart from helm repo or branch/tag of git repo
  #     path: ""                        # Optional - if git repo was provided as repoURL, provide path to the helm chart in git repo
  #     ignoreMissingValueFiles: false  # Optional - set to true if you want to ignore missing values files (define only required ones), false by default
  #     skipCrds: false                 # Optional - set to true if you want to skip CRDs deployment by Helm, false by default
  - name: standard-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
        - standard
        - standard-nonprod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - standard
          - standard-prod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
        - standard
        - standard-aux
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
          - aux011
  - name: shared-secrets
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
        - standard
        - standard-nonprod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - standard
          - standard-prod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - standard
          - standard-aux
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
          - aux011
  - name: onegateway-workload
    containerOS: linux
    chart:
      ignoreMissingValueFiles: true
    environments:
      - name: nonprod
        namespaces:
          - onegateway
          - onegateway-nonprod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
          - onegateway-prod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
          - onegateway-aux
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
  - name: onegateway-sessionmanager
    containerOS: linux
    chart:
      ignoreMissingValueFiles: true
    environments:
      - name: nonprod
        namespaces:
          - onegateway
          - onegateway-nonprod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
          - onegateway-prod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
          - onegateway-aux
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
  - name: onegateway-redis
    chart:
      ignoreMissingValueFiles: true
      path: "kubeit-redis-chart"
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - onegateway
          - onegateway-nonprod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
          - onegateway-prod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
          - onegateway-aux
        region:
          - westeurope
        clusterColour:
          - blue
  - name: win-standard-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - win-standard-workload
          - win-standard-workload-nonprod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - win-standard-workload
          - win-standard-workload-prod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - win-standard-workload
          - win-standard-workload-aux
        region:
          - westeurope
        clusterColour:
          - blue
          - green
          - aux011
